# Generated by Django 2.2.13 on 2020-06-27 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='etime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 27, 11, 41, 8, 558111)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='stime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 27, 11, 41, 8, 558111)),
        ),
    ]
