# Generated by Django 2.2.13 on 2020-06-28 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200627_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('S', 'Sports'), ('D', 'Department'), ('A', 'Auditorium'), ('F', 'Food')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='etime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 28, 14, 42, 30, 783080)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='stime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 28, 14, 42, 30, 783080)),
        ),
    ]
