# Generated by Django 2.2.13 on 2020-06-28 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200628_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stime', models.TimeField(default=datetime.datetime(2020, 6, 28, 14, 51, 6, 187987))),
                ('etime', models.TimeField(default=datetime.datetime(2020, 6, 28, 14, 51, 6, 187987))),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('D', 'Department'), ('A', 'Auditorium'), ('F', 'Food'), ('S', 'Sports')], max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='api.Place'),
        ),
    ]
