# Generated by Django 2.2.13 on 2020-06-28 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200628_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='etime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 28, 14, 51, 12, 436766)),
        ),
        migrations.AlterField(
            model_name='event',
            name='stime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 28, 14, 51, 12, 436766)),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('A', 'Auditorium'), ('F', 'Food'), ('S', 'Sports'), ('D', 'Department')], max_length=50),
        ),
    ]
