# Generated by Django 2.2.13 on 2020-06-28 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200628_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 28)),
        ),
        migrations.AlterField(
            model_name='event',
            name='etime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 28, 15, 2, 6, 82904)),
        ),
        migrations.AlterField(
            model_name='event',
            name='stime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 28, 15, 2, 6, 82904)),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('A', 'Auditorium'), ('D', 'Department'), ('S', 'Sports'), ('F', 'Food')], max_length=50),
        ),
    ]
