# Generated by Django 2.2.13 on 2020-06-28 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200628_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayschedule',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='etime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 28, 15, 2, 35, 162330)),
        ),
        migrations.AlterField(
            model_name='event',
            name='stime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 28, 15, 2, 35, 162330)),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('F', 'Food'), ('S', 'Sports'), ('D', 'Department'), ('A', 'Auditorium')], max_length=50),
        ),
    ]
