# Generated by Django 2.2.13 on 2020-07-31 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200628_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='imgname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='etime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 31, 11, 30, 16, 410791)),
        ),
        migrations.AlterField(
            model_name='event',
            name='stime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 31, 11, 30, 16, 410791)),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('A', 'Auditorium'), ('D', 'Department'), ('S', 'Sports'), ('F', 'Food')], max_length=50),
        ),
    ]
