# Generated by Django 2.2.13 on 2020-08-02 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200731_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imgname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='events',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='etime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 2, 22, 1, 57, 77581), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='stime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 2, 22, 1, 57, 77581), null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('F', 'Food'), ('D', 'Department'), ('S', 'Sports'), ('A', 'Auditorium')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='imgname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
