# Generated by Django 2.2.13 on 2020-08-03 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200802_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='imgname',
        ),
        migrations.AlterField(
            model_name='event',
            name='etime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 3, 12, 18, 0, 275271), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='stime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 3, 12, 18, 0, 274275), null=True),
        ),
    ]
