# Generated by Django 2.2.13 on 2020-08-22 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200803_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='etime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 22, 22, 13, 7, 190616), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='stime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 22, 22, 13, 7, 190616), null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('S', 'Sports'), ('D', 'Department'), ('F', 'Food'), ('A', 'Auditorium')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(default='Description', max_length=10000),
        ),
        migrations.AlterField(
            model_name='place',
            name='imgname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
