# Generated by Django 2.2.13 on 2020-09-07 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200822_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='etime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 7, 14, 47, 9, 246687), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='stime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 7, 14, 47, 9, 246687), null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('A', 'Auditorium'), ('D', 'Department'), ('F', 'Food'), ('S', 'Sports')], max_length=50, null=True),
        ),
    ]
